# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stat 550 - W2021
email: daniel@stat.ubc.ca
author: Daniel J. McDonald
author-url: https://dajmcdon.github.io/
description: > # this means to ignore newlines until "baseurl:"
  The course website for UBC's Stat 550 - Statistical Consulting
baseurl: "" # the subpath of your site, e.g. 
url: "" # the base hostname & protocol for your site, e.g. https://example.com
lang: en # language can also be set on a per page basis. Primary use right now is only for <html lang="">

# Build settings
markdown: kramdown
theme: minimal-course
permalink: /:title/
navbar: light          # other options: dark
theme-bg: rgb(12, 127, 135)
navbar-fixed-top: true # if true, also check _sass/bootstrap4-cdn.scss padding top
logo_path: /assets/img/american-sign-language-interpreting-solid.svg

google_fonts: Montserrat

use-license: true

navigation:
  - title: Syllabus
    url: https://stat550-2021.github.io/syllabus/
  - title: Schedule
    url: https://stat550-2021.github.io/schedule/
  - title: Github
    url: https://github.com/stat550-2021/
    icon: "fab fa-github"

